<?php
/**
 * Archive Template
 *
 * Handles category, tag, author, and date archives.
 * The archive title is generated by get_the_archive_title() which
 * prepends the appropriate label (Category:, Tag:, Author:, etc.).
 *
 * @package PodNest
 */

defined( 'ABSPATH' ) || exit;

get_header();
?>

<div class="pn-page-hero">
    <div class="pn-container">
        <?php podnest_breadcrumbs(); ?>
        <h1><?php the_archive_title(); ?></h1>
        <?php the_archive_description( '<p class="pn-lead" style="margin-top:12px;">', '</p>' ); ?>
    </div>
</div>

<div class="pn-container" style="padding-top:60px;padding-bottom:80px;">
    <?php if ( have_posts() ) : ?>

        <div class="pn-blog-grid">
            <?php while ( have_posts() ) : the_post(); ?>
            <article id="post-<?php the_ID(); ?>" <?php post_class( 'pn-blog-card' ); ?>>
                <?php if ( has_post_thumbnail() ) : ?>
                <a href="<?php the_permalink(); ?>" tabindex="-1" aria-hidden="true">
                    <?php the_post_thumbnail( 'podnest-thumb' ); ?>
                </a>
                <?php endif; ?>
                <div class="pn-blog-card-body">
                    <time datetime="<?php echo esc_attr( get_the_date( 'c' ) ); ?>" class="pn-blog-date">
                        <?php echo esc_html( get_the_date() ); ?>
                    </time>
                    <h2><a href="<?php the_permalink(); ?>"><?php the_title(); ?></a></h2>
                    <p><?php echo esc_html( wp_trim_words( get_the_excerpt(), 22, '…' ) ); ?></p>
                </div>
            </article>
            <?php endwhile; ?>
        </div>

        <?php the_posts_pagination( [
            'prev_text' => '← ' . __( 'Newer', 'podnest' ),
            'next_text' => __( 'Older', 'podnest' ) . ' →',
            'class'     => 'pn-pagination',
        ] ); ?>

    <?php else : ?>
        <p class="pn-muted" style="text-align:center;padding:60px 0;">
            <?php esc_html_e( 'No posts found in this archive.', 'podnest' ); ?>
        </p>
    <?php endif; ?>
</div>

<?php get_footer(); ?>
